### ISSUE TITLE
cannot use .env to set DJANGO_SECRET_KEY

### ISSUE THREAD

**Issue by gautamkrishnar** [rebuildearth/OpenSalve#5]
While running migration script it is throwing the error:
```bash
(OpenSlaveAPI) gautam@api:~/workspace/OpenSlaveAPI$ cat .env
DJANGO_SECRET_KEY='D^#c09H&zwaCjJ!*l0PYr%q!iSToS=jGZlvl(dfXqds2m%W8fW9@_+_JIKBCJrpsf)Xc+5t6J6X$j$&vFGq1wO8Ic1hw7px'

(OpenSlaveAPI) gautam@api:~/workspace/OpenSlaveAPI$ python3 manage.py makemigrations && python manage.py migrate
Traceback (most recent call last):
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/environ/environ.py", line 273, in get_value
    value = self.ENVIRON[var]
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'D^#c09H&zwaCjJ!*l0PYr%q!iSToS=jGZlvl(dfXqds2m%W8fW9@_+_JIKBCJrpsf)Xc+5t6J6X$j$&vFGq1wO8Ic1hw7px'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 12, in <module>
    from django.db.migrations.autodetector import MigrationAutodetector
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/db/migrations/autodetector.py", line 11, in <module>
    from django.db.migrations.questioner import MigrationQuestioner
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/db/migrations/questioner.py", line 9, in <module>
    from .loader import MigrationLoader
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/db/migrations/loader.py", line 8, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 9, in <module>
    class MigrationRecorder:
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 22, in MigrationRecorder
    class Migration(models.Model):
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/db/models/base.py", line 87, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/apps/registry.py", line 249, in get_containing_app_config
    self.check_apps_ready()
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/apps/registry.py", line 131, in check_apps_ready
    settings.INSTALLED_APPS
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/gautam/workspace/OpenSlaveAPI/opensalve/settings.py", line 34, in <module>
    SECRET_KEY = env('DJANGO_SECRET_KEY')
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/environ/environ.py", line 123, in __call__
    return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/environ/environ.py", line 284, in get_value
    value = self.get_value(value, cast=cast, default=default)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/environ/environ.py", line 277, in get_value
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the D^#c09H&zwaCjJ!*l0PYr%q!iSToS=jGZlvl(dfXqds2m%W8fW9@_+_JIKBCJrpsf)Xc+5t6J6X$j$&vFGq1wO8Ic1hw7px environment variable
```

Python version: 3.6.8

**Comment by gautamkrishnar** [comment]
This was an environment specific error.
