### ISSUE TITLE
Cant run makemigrations

### ISSUE THREAD

**Issue by gautamkrishnar** [rebuildearth/OpenSalve#6]
while running  `python3 manage.py makemigrations && python manage.py` i am getting the following error:

```bash
$ pipenv run python manage.py makemigrations
Loading .env environment variables…
Traceback (most recent call last):
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/drf_yasg/generators.py", line 11, in <module>
    from rest_framework.schemas.generators import SchemaGenerator, endpoint_ordering
ImportError: cannot import name 'SchemaGenerator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/urls/resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gautam/workspace/OpenSlaveAPI/opensalve/urls.py", line 19, in <module>
    from drf_yasg.views import get_schema_view
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/drf_yasg/views.py", line 48, in <module>
    generator_class=swagger_settings.DEFAULT_GENERATOR_CLASS,
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/drf_yasg/app_settings.py", line 111, in __getattr__
    val = perform_import(val, attr)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/rest_framework/settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "/home/gautam/.local/share/virtualenvs/OpenSlaveAPI-WVGInhZm/lib/python3.6/site-packages/rest_framework/settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'drf_yasg.generators.OpenAPISchemaGenerator' for API setting 'DEFAULT_GENERATOR_CLASS'. ImportError: cannot import name 'SchemaGenerator'.
```

**Comment by raeeska** [comment]
Looks like this started after the following change in the Pipfile
djangorestframework = ">=3.9.1"

Was able to run makemigrations, after reverting it to
djangorestframework = "==3.8.2"

**Comment by gautamkrishnar** [comment]
@raeeska can you open a PR to fix this?

**Comment by raeeska** [comment]
Opened PR #7
